/*
  # Continuous Learning OSINT System with Mechanical Synthesis LLM

  ## Overview
  This migration creates a sophisticated autonomous learning system that continuously
  collects OSINT data, learns from it, builds a knowledge graph, and generates
  intelligent syntheses using a mechanical LLM approach with adaptive templates.

  ## 1. New Tables

  ### `osint_learning_sessions`
  Tracks continuous learning sessions and their outcomes.
  - `id` (uuid, primary key) - Unique identifier
  - `session_start` (timestamptz) - Session start time
  - `session_end` (timestamptz) - Session end time
  - `topics_analyzed` (text[]) - Array of topics processed
  - `sources_consulted` (integer) - Number of sources checked
  - `new_knowledge_count` (integer) - New concepts discovered
  - `synthesis_quality_score` (numeric) - Average quality score (0-100)
  - `model_version` (text) - NLP model version identifier
  - `metadata` (jsonb) - Additional session data
  - `created_at` (timestamptz) - Record creation time

  ### `knowledge_graph_nodes`
  Stores entities and concepts discovered through OSINT.
  - `id` (uuid, primary key) - Unique identifier
  - `entity_type` (text) - Type: person, organization, location, concept, event, technology
  - `entity_name` (text, indexed) - Canonical entity name
  - `aliases` (text[]) - Alternative names
  - `confidence_score` (numeric) - Confidence in entity existence (0-100)
  - `first_seen` (timestamptz) - First detection time
  - `last_updated` (timestamptz) - Last update time
  - `mention_count` (integer) - Total mentions across sources
  - `importance_score` (numeric) - Calculated importance (0-100)
  - `embedding` (vector(768)) - Entity embedding for similarity
  - `attributes` (jsonb) - Dynamic entity attributes
  - `sources` (uuid[]) - Array of indexed_pages references
  - `created_at` (timestamptz) - Record creation time

  ### `knowledge_graph_edges`
  Stores relationships between entities.
  - `id` (uuid, primary key) - Unique identifier
  - `source_node_id` (uuid, foreign key) - Source entity
  - `target_node_id` (uuid, foreign key) - Target entity
  - `relationship_type` (text) - Type: related_to, part_of, caused_by, located_in, etc.
  - `confidence_score` (numeric) - Confidence in relationship (0-100)
  - `strength` (numeric) - Relationship strength (0-100)
  - `evidence_count` (integer) - Number of supporting sources
  - `evidence_sources` (uuid[]) - Array of indexed_pages references
  - `first_detected` (timestamptz) - First detection time
  - `last_confirmed` (timestamptz) - Last confirmation time
  - `metadata` (jsonb) - Additional relationship data
  - `created_at` (timestamptz) - Record creation time

  ### `learned_patterns`
  Stores patterns discovered by the NLP engine.
  - `id` (uuid, primary key) - Unique identifier
  - `pattern_type` (text) - Type: linguistic, temporal, causal, statistical
  - `pattern_description` (text) - Human-readable description
  - `pattern_data` (jsonb) - Structured pattern data
  - `confidence_score` (numeric) - Pattern reliability (0-100)
  - `occurrence_count` (integer) - Times pattern observed
  - `last_observed` (timestamptz) - Last observation time
  - `domain` (text) - Subject domain if applicable
  - `embedding` (vector(384)) - Pattern embedding
  - `created_at` (timestamptz) - Record creation time

  ### `synthesis_templates`
  Stores adaptive templates for the mechanical LLM.
  - `id` (uuid, primary key) - Unique identifier
  - `template_name` (text, indexed) - Template identifier
  - `template_category` (text) - Category: narrative, analytical, comparative, temporal
  - `style` (text) - Style: journalistic, academic, conversational, technical
  - `structure` (jsonb) - Template structure with placeholders
  - `usage_count` (integer) - Times template used
  - `success_rate` (numeric) - Quality score average (0-100)
  - `adaptations` (jsonb) - Learned adaptations over time
  - `conditions` (jsonb) - Conditions for template selection
  - `examples` (jsonb) - Example outputs
  - `created_at` (timestamptz) - Record creation time
  - `updated_at` (timestamptz) - Last update time

  ### `mechanical_syntheses`
  Stores syntheses generated by the mechanical LLM.
  - `id` (uuid, primary key) - Unique identifier
  - `query` (text) - Original query
  - `synthesis_text` (text) - Generated synthesis
  - `template_id` (uuid, foreign key) - Template used
  - `style_used` (text) - Style applied
  - `source_nodes` (uuid[]) - Knowledge graph nodes used
  - `source_pages` (uuid[]) - Indexed pages referenced
  - `confidence_score` (numeric) - Overall confidence (0-100)
  - `coherence_score` (numeric) - Narrative coherence (0-100)
  - `citation_count` (integer) - Number of citations
  - `generation_time_ms` (integer) - Time to generate
  - `user_feedback` (jsonb) - User ratings and feedback
  - `metadata` (jsonb) - Additional generation metadata
  - `created_at` (timestamptz) - Record creation time

  ### `learning_tasks_queue`
  Background task queue for continuous learning.
  - `id` (uuid, primary key) - Unique identifier
  - `task_type` (text) - Type: osint_scan, knowledge_update, pattern_detection, graph_consolidation
  - `priority` (integer) - Priority 1-10 (higher = more urgent)
  - `status` (text) - Status: pending, processing, completed, failed
  - `scheduled_for` (timestamptz) - When to execute
  - `parameters` (jsonb) - Task parameters
  - `result` (jsonb) - Task result data
  - `started_at` (timestamptz) - Execution start time
  - `completed_at` (timestamptz) - Execution completion time
  - `error_message` (text) - Error if failed
  - `retry_count` (integer) - Number of retries
  - `created_at` (timestamptz) - Record creation time

  ### `osint_data_cache`
  Fast cache for frequently accessed OSINT data.
  - `id` (uuid, primary key) - Unique identifier
  - `cache_key` (text, unique, indexed) - Cache lookup key
  - `cache_type` (text) - Type: query_result, entity_data, pattern_match
  - `data` (jsonb) - Cached data
  - `freshness_score` (numeric) - Data freshness (0-100)
  - `hit_count` (integer) - Times accessed
  - `expires_at` (timestamptz) - Expiration time
  - `created_at` (timestamptz) - Record creation time
  - `last_accessed` (timestamptz) - Last access time

  ### `learning_metrics`
  Tracks system performance and learning progress.
  - `id` (uuid, primary key) - Unique identifier
  - `metric_type` (text) - Type: knowledge_growth, synthesis_quality, pattern_accuracy
  - `metric_value` (numeric) - Metric value
  - `time_window` (text) - Time period: hourly, daily, weekly
  - `metadata` (jsonb) - Additional metric data
  - `recorded_at` (timestamptz) - Measurement time

  ## 2. Indexes
  - Performance indexes on frequently queried fields
  - Vector similarity indexes for embeddings
  - GIN indexes for array and JSONB fields

  ## 3. Security (RLS)
  - Public read access to knowledge graph and syntheses
  - System-only write access to learning tables
  - Audit logging for sensitive operations

  ## 4. Functions
  - Automatic timestamp updates
  - Knowledge graph consolidation
  - Pattern detection triggers
*/

-- Enable required extensions (if not already enabled)
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ================================================
-- TABLE DEFINITIONS
-- ================================================

-- Learning sessions tracking
CREATE TABLE IF NOT EXISTS osint_learning_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_start timestamptz NOT NULL DEFAULT now(),
  session_end timestamptz,
  topics_analyzed text[] DEFAULT '{}',
  sources_consulted integer DEFAULT 0,
  new_knowledge_count integer DEFAULT 0,
  synthesis_quality_score numeric(5,2) DEFAULT 0 CHECK (synthesis_quality_score >= 0 AND synthesis_quality_score <= 100),
  model_version text NOT NULL DEFAULT '1.0.0',
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- Knowledge graph nodes (entities and concepts)
CREATE TABLE IF NOT EXISTS knowledge_graph_nodes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type text NOT NULL CHECK (entity_type IN ('person', 'organization', 'location', 'concept', 'event', 'technology', 'other')),
  entity_name text NOT NULL,
  aliases text[] DEFAULT '{}',
  confidence_score numeric(5,2) DEFAULT 50 CHECK (confidence_score >= 0 AND confidence_score <= 100),
  first_seen timestamptz DEFAULT now(),
  last_updated timestamptz DEFAULT now(),
  mention_count integer DEFAULT 1,
  importance_score numeric(5,2) DEFAULT 50 CHECK (importance_score >= 0 AND importance_score <= 100),
  embedding vector(768),
  attributes jsonb DEFAULT '{}'::jsonb,
  sources uuid[] DEFAULT '{}',
  created_at timestamptz DEFAULT now()
);

-- Knowledge graph edges (relationships)
CREATE TABLE IF NOT EXISTS knowledge_graph_edges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_node_id uuid NOT NULL REFERENCES knowledge_graph_nodes(id) ON DELETE CASCADE,
  target_node_id uuid NOT NULL REFERENCES knowledge_graph_nodes(id) ON DELETE CASCADE,
  relationship_type text NOT NULL,
  confidence_score numeric(5,2) DEFAULT 50 CHECK (confidence_score >= 0 AND confidence_score <= 100),
  strength numeric(5,2) DEFAULT 50 CHECK (strength >= 0 AND strength <= 100),
  evidence_count integer DEFAULT 1,
  evidence_sources uuid[] DEFAULT '{}',
  first_detected timestamptz DEFAULT now(),
  last_confirmed timestamptz DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- Learned patterns from NLP
CREATE TABLE IF NOT EXISTS learned_patterns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pattern_type text NOT NULL CHECK (pattern_type IN ('linguistic', 'temporal', 'causal', 'statistical', 'other')),
  pattern_description text NOT NULL,
  pattern_data jsonb NOT NULL,
  confidence_score numeric(5,2) DEFAULT 50 CHECK (confidence_score >= 0 AND confidence_score <= 100),
  occurrence_count integer DEFAULT 1,
  last_observed timestamptz DEFAULT now(),
  domain text,
  embedding vector(384),
  created_at timestamptz DEFAULT now()
);

-- Synthesis templates for mechanical LLM
CREATE TABLE IF NOT EXISTS synthesis_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_name text NOT NULL,
  template_category text NOT NULL CHECK (template_category IN ('narrative', 'analytical', 'comparative', 'temporal', 'explanatory')),
  style text NOT NULL CHECK (style IN ('journalistic', 'academic', 'conversational', 'technical', 'formal')),
  structure jsonb NOT NULL,
  usage_count integer DEFAULT 0,
  success_rate numeric(5,2) DEFAULT 50 CHECK (success_rate >= 0 AND success_rate <= 100),
  adaptations jsonb DEFAULT '{}'::jsonb,
  conditions jsonb DEFAULT '{}'::jsonb,
  examples jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Mechanical syntheses generated
CREATE TABLE IF NOT EXISTS mechanical_syntheses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  query text NOT NULL,
  synthesis_text text NOT NULL,
  template_id uuid REFERENCES synthesis_templates(id) ON DELETE SET NULL,
  style_used text NOT NULL,
  source_nodes uuid[] DEFAULT '{}',
  source_pages uuid[] DEFAULT '{}',
  confidence_score numeric(5,2) DEFAULT 50 CHECK (confidence_score >= 0 AND confidence_score <= 100),
  coherence_score numeric(5,2) DEFAULT 50 CHECK (coherence_score >= 0 AND coherence_score <= 100),
  citation_count integer DEFAULT 0,
  generation_time_ms integer DEFAULT 0,
  user_feedback jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- Background learning tasks queue
CREATE TABLE IF NOT EXISTS learning_tasks_queue (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_type text NOT NULL CHECK (task_type IN ('osint_scan', 'knowledge_update', 'pattern_detection', 'graph_consolidation', 'cache_refresh', 'quality_assessment')),
  priority integer DEFAULT 5 CHECK (priority >= 1 AND priority <= 10),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'cancelled')),
  scheduled_for timestamptz DEFAULT now(),
  parameters jsonb DEFAULT '{}'::jsonb,
  result jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  error_message text,
  retry_count integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- Fast OSINT data cache
CREATE TABLE IF NOT EXISTS osint_data_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cache_key text UNIQUE NOT NULL,
  cache_type text NOT NULL CHECK (cache_type IN ('query_result', 'entity_data', 'pattern_match', 'synthesis', 'other')),
  data jsonb NOT NULL,
  freshness_score numeric(5,2) DEFAULT 100 CHECK (freshness_score >= 0 AND freshness_score <= 100),
  hit_count integer DEFAULT 0,
  expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now(),
  last_accessed timestamptz DEFAULT now()
);

-- Learning metrics and analytics
CREATE TABLE IF NOT EXISTS learning_metrics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  metric_type text NOT NULL CHECK (metric_type IN ('knowledge_growth', 'synthesis_quality', 'pattern_accuracy', 'cache_hit_rate', 'learning_speed', 'other')),
  metric_value numeric NOT NULL,
  time_window text NOT NULL CHECK (time_window IN ('hourly', 'daily', 'weekly', 'monthly')),
  metadata jsonb DEFAULT '{}'::jsonb,
  recorded_at timestamptz DEFAULT now()
);

-- ================================================
-- INDEXES FOR PERFORMANCE
-- ================================================

-- Learning sessions
CREATE INDEX IF NOT EXISTS idx_learning_sessions_start ON osint_learning_sessions(session_start DESC);
CREATE INDEX IF NOT EXISTS idx_learning_sessions_model ON osint_learning_sessions(model_version);

-- Knowledge graph nodes
CREATE INDEX IF NOT EXISTS idx_kg_nodes_entity_name ON knowledge_graph_nodes(entity_name);
CREATE INDEX IF NOT EXISTS idx_kg_nodes_entity_type ON knowledge_graph_nodes(entity_type);
CREATE INDEX IF NOT EXISTS idx_kg_nodes_importance ON knowledge_graph_nodes(importance_score DESC);
CREATE INDEX IF NOT EXISTS idx_kg_nodes_last_updated ON knowledge_graph_nodes(last_updated DESC);
CREATE INDEX IF NOT EXISTS idx_kg_nodes_embedding ON knowledge_graph_nodes USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS idx_kg_nodes_sources ON knowledge_graph_nodes USING gin(sources);

-- Knowledge graph edges
CREATE INDEX IF NOT EXISTS idx_kg_edges_source ON knowledge_graph_edges(source_node_id);
CREATE INDEX IF NOT EXISTS idx_kg_edges_target ON knowledge_graph_edges(target_node_id);
CREATE INDEX IF NOT EXISTS idx_kg_edges_type ON knowledge_graph_edges(relationship_type);
CREATE INDEX IF NOT EXISTS idx_kg_edges_confidence ON knowledge_graph_edges(confidence_score DESC);

-- Learned patterns
CREATE INDEX IF NOT EXISTS idx_patterns_type ON learned_patterns(pattern_type);
CREATE INDEX IF NOT EXISTS idx_patterns_confidence ON learned_patterns(confidence_score DESC);
CREATE INDEX IF NOT EXISTS idx_patterns_observed ON learned_patterns(last_observed DESC);
CREATE INDEX IF NOT EXISTS idx_patterns_embedding ON learned_patterns USING ivfflat (embedding vector_cosine_ops) WITH (lists = 50);

-- Synthesis templates
CREATE INDEX IF NOT EXISTS idx_templates_name ON synthesis_templates(template_name);
CREATE INDEX IF NOT EXISTS idx_templates_category ON synthesis_templates(template_category);
CREATE INDEX IF NOT EXISTS idx_templates_style ON synthesis_templates(style);
CREATE INDEX IF NOT EXISTS idx_templates_success ON synthesis_templates(success_rate DESC);

-- Mechanical syntheses
CREATE INDEX IF NOT EXISTS idx_syntheses_created ON mechanical_syntheses(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_syntheses_template ON mechanical_syntheses(template_id);
CREATE INDEX IF NOT EXISTS idx_syntheses_confidence ON mechanical_syntheses(confidence_score DESC);
CREATE INDEX IF NOT EXISTS idx_syntheses_source_nodes ON mechanical_syntheses USING gin(source_nodes);
CREATE INDEX IF NOT EXISTS idx_syntheses_source_pages ON mechanical_syntheses USING gin(source_pages);

-- Learning tasks queue
CREATE INDEX IF NOT EXISTS idx_tasks_status ON learning_tasks_queue(status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON learning_tasks_queue(priority DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_scheduled ON learning_tasks_queue(scheduled_for);
CREATE INDEX IF NOT EXISTS idx_tasks_type ON learning_tasks_queue(task_type);

-- Cache
CREATE INDEX IF NOT EXISTS idx_cache_key ON osint_data_cache(cache_key);
CREATE INDEX IF NOT EXISTS idx_cache_type ON osint_data_cache(cache_type);
CREATE INDEX IF NOT EXISTS idx_cache_expires ON osint_data_cache(expires_at);

-- Metrics
CREATE INDEX IF NOT EXISTS idx_metrics_type ON learning_metrics(metric_type);
CREATE INDEX IF NOT EXISTS idx_metrics_recorded ON learning_metrics(recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_metrics_window ON learning_metrics(time_window);

-- ================================================
-- ROW LEVEL SECURITY
-- ================================================

ALTER TABLE osint_learning_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_graph_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_graph_edges ENABLE ROW LEVEL SECURITY;
ALTER TABLE learned_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE synthesis_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE mechanical_syntheses ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_tasks_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE osint_data_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_metrics ENABLE ROW LEVEL SECURITY;

-- Public read access to knowledge graph
CREATE POLICY "Public can view knowledge graph nodes"
  ON knowledge_graph_nodes FOR SELECT
  USING (true);

CREATE POLICY "Public can view knowledge graph edges"
  ON knowledge_graph_edges FOR SELECT
  USING (true);

-- Public read access to syntheses
CREATE POLICY "Public can view mechanical syntheses"
  ON mechanical_syntheses FOR SELECT
  USING (true);

-- Public read access to templates
CREATE POLICY "Public can view synthesis templates"
  ON synthesis_templates FOR SELECT
  USING (true);

-- Public read access to learning sessions (for monitoring)
CREATE POLICY "Public can view learning sessions"
  ON osint_learning_sessions FOR SELECT
  USING (true);

-- Public read access to patterns
CREATE POLICY "Public can view learned patterns"
  ON learned_patterns FOR SELECT
  USING (true);

-- Public read access to cache
CREATE POLICY "Public can view cache entries"
  ON osint_data_cache FOR SELECT
  USING (true);

-- Public read access to metrics
CREATE POLICY "Public can view learning metrics"
  ON learning_metrics FOR SELECT
  USING (true);

-- Public read access to tasks (for monitoring)
CREATE POLICY "Public can view learning tasks"
  ON learning_tasks_queue FOR SELECT
  USING (true);

-- ================================================
-- INITIAL DATA: SYNTHESIS TEMPLATES
-- ================================================

INSERT INTO synthesis_templates (template_name, template_category, style, structure, conditions, examples)
VALUES
  (
    'factual_summary',
    'narrative',
    'journalistic',
    '{
      "intro": "Based on analysis of {source_count} sources, here is what we know about {query}:",
      "body_structure": ["fact_statements", "source_citations", "temporal_context"],
      "conclusion": "This information was compiled from {source_list} on {date}."
    }'::jsonb,
    '{"min_sources": 3, "confidence_threshold": 60}'::jsonb,
    '[]'::jsonb
  ),
  (
    'analytical_deep_dive',
    'analytical',
    'academic',
    '{
      "intro": "An analysis of {query} reveals several key dimensions:",
      "body_structure": ["thesis_statement", "supporting_evidence", "counterarguments", "synthesis"],
      "conclusion": "In conclusion, the available evidence suggests {conclusion_statement}."
    }'::jsonb,
    '{"min_sources": 5, "complexity": "high"}'::jsonb,
    '[]'::jsonb
  ),
  (
    'comparative_analysis',
    'comparative',
    'formal',
    '{
      "intro": "Comparing {entity_a} and {entity_b} across {aspect}:",
      "body_structure": ["similarities", "differences", "context", "implications"],
      "conclusion": "The comparison reveals {key_insight}."
    }'::jsonb,
    '{"requires_entities": 2}'::jsonb,
    '[]'::jsonb
  ),
  (
    'temporal_narrative',
    'temporal',
    'journalistic',
    '{
      "intro": "The evolution of {query} over time shows the following progression:",
      "body_structure": ["timeline_events", "causal_links", "turning_points", "current_state"],
      "conclusion": "This chronological analysis indicates {trend_direction}."
    }'::jsonb,
    '{"requires_temporal_data": true}'::jsonb,
    '[]'::jsonb
  ),
  (
    'conversational_explanation',
    'explanatory',
    'conversational',
    '{
      "intro": "Let me explain {query} in simple terms:",
      "body_structure": ["core_concept", "examples", "analogies", "key_takeaways"],
      "conclusion": "To sum up, {summary_statement}."
    }'::jsonb,
    '{"complexity": "low", "audience": "general"}'::jsonb,
    '[]'::jsonb
  )
ON CONFLICT DO NOTHING;

-- ================================================
-- INITIAL LEARNING TASK
-- ================================================

INSERT INTO learning_tasks_queue (task_type, priority, parameters)
VALUES
  ('osint_scan', 8, '{"topics": ["technology trends", "global events"], "depth": "exploratory"}'::jsonb),
  ('knowledge_update', 7, '{"consolidate_duplicates": true}'::jsonb),
  ('pattern_detection', 6, '{"pattern_types": ["temporal", "causal"]}'::jsonb)
ON CONFLICT DO NOTHING;
